### ISSUE TITLE
Experiments YAML requiring with_indifferent_access

### ISSUE THREAD

**Issue by rtwomey** [splitrb/split#123]
I noticed that in order to load a YAML experiments file, I need to specify with_indifferent_access. Here's an example experiments file:

``` yaml
registration_link:
  alternatives:
    - Get Started
    - Register
  resettable: false
```

I then modify my initializer so that:

``` ruby
Split.configure do |config|
  config.experiments = YAML.load_file('config/experiments.yml').with_indifferent_access
end
```

I think the culprit is [how you're referencing alternatives](https://github.com/andrew/split/blob/master/lib/split/configuration.rb#L94) in the config file.

Is this intentional? If so, might be good to update the README. If this is a bug, I'd be happy to write a failing test case and send you a PR when I get a few minutes.
