### ISSUE TITLE
finishing goals with metrics

### ISSUE THREAD

**Issue by btucker** [splitrb/split#394]
I'd like to be able to use a metric to finish a goal of an experiment.  In my reading of the code, this is not currently possible.  What I'm wondering about implementing would look like this:

``` yaml
my_experment:
  alternatives:
     # ...
   goals:
      - name: my_goal1
        metrics: 
          - metric1
          - metric2
```

`metrics` under a `goal` would have the same semantics as defining metrics at the `experiment` level.  I believe the implementation would rely on a change to `Split::Metric.find` to find metrics referenced by goals.  But I haven't dug into the source too deeply yet.

The purpose of this is to allow a single metric to be used to finish either multiple goals in multiple experiments.

Is this making sense?  If so, I'll take a stab at a PR for this.
